### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by linuzzx** [aloussase/alexandria-app#13]
So I'm German but also speaking English, but the app just displays in spanish or something like that :/

**Comment by aloussase** [comment]
Hi yeah sorry for that just noticed. I missed some translations, I will make sure to include them for the next update.

**Comment by aloussase** [comment]
Changes have been implemented. Expect to see them once the new version hits the fdroid store.

**Comment by linuzzx** [comment]
Doesn't seem to be fixed in the latest update :/

**Comment by aloussase** [comment]
Hi! What issue persists? All english translations should be correctly set now. I can't do german translations as I do not speak the language myself. A user sent me russian translations that i plan on adding for the next update. You could do the same for german if you want to.

**Comment by linuzzx** [comment]
The only issue is that I can't change the language and english isn't the default :/

**Comment by aloussase** [comment]
Ahh you're right, that is a problem. Originally I made this app for my mom, that's why default is spanish. I'll add an option to choose language.

**Comment by aloussase** [comment]
I have added an option to change the app language. Will be available in the next update.

**Comment by Delorean12DMC** [comment]
Im having the same issue, that i can't change the language manually. Im German too and i can help you with the translations, if you still need help.

**Comment by aloussase** [comment]
@Delorean12DMC in the latest version (which should be on FDroid next week or so) I've implemented the ability to manually change the language. If you want to contribute a strings file for german it would be great as well!

**Comment by Delorean12DMC** [comment]
> @Delorean12DMC in the latest version (which should be on FDroid next week or so) I've implemented the ability to manually change the language. If you want to contribute a strings file for german it would be great as well!

That sounds great!

If course i want, im already on it. But i never contributed here. Do i need to make a push or how can i do it?

**Comment by Delorean12DMC** [comment]
> You need to fork this repository and create a new branch on your fork. Then, on that branch, make the necessary changes and commit them. Then you can open a pull request which I'll review.
> 
> Otherwise, I you do not have much experience with Git and Github, I could also accept the file by email, but please make sure all necessary translations are included.

Okay i did an pull request, did it all on my phone with termux, so... Sorry i pushed twice. :D

It's no problem, i just needed directions on how to do it and i think besides my little mistake, i did fine. 

So as you can see i just added the german translation files and corrected the english and spanish translation_options files where i added german.

I don't know what or if something needs to get changed for the German language to work, i don't use Kotlin, so it's up to you. Sorry for that, but i think the files will help you.

PS: I honestly don't know what the string "download_receiver_description" is used for, so i hope the translation is correct. If you could explain me in what case or where it gets used, i can check if the string makes sense or not.

**Comment by aloussase** [comment]
Thank you @Delorean12DMC , now Alexandria supports German! Changes should be available on next update in FDroid

**Comment by Delorean12DMC** [comment]
That sounds great! Im happy that i could help you.

Did you check the string for: `download_receiver_description`?

Because as i said, i really dont know the use case of the string. Even in your spanish language file it was english.

**Comment by aloussase** [comment]
Yes, that string is really just used internally, so it doesn't really matter what it says haha
