### ISSUE TITLE
Internet connection sources

### ISSUE THREAD

**Issue by shuvashish76** [aloussase/alexandria-app#6]
Hello, can you please mention exactly which internet sources it connects to for downloading books/covers etc, also sites for uploading ebooks for the conversion?

It requires [some Anti-feature ](https://f-droid.org/en/docs/Anti-Features/#NonFreeNet)tag on F-Droid as it connects to some Non-Free sites : https://gitlab.com/fdroid/fdroiddata/-/issues/3206

**Comment by aloussase** [comment]
Hi! I doesn't connect to non-free sites. I uses libgen for books and an API I made for book conversions.

**Comment by licaon-kter** [comment]
https://f-droid.org/docs/Anti-Features/#NonFreeNet

> **Non-Free Network Services**
>
> This Anti-Feature is applied to apps that promote or depend entirely on a Non-Free network service, or any service which is impossible, or not easy to replace. Replacement requires changes to the app or service. **This antifeature would not apply, if there is a simple configuration option that allows pointing the app to a running instance of an alternative, publicly available, self-hostable, free software server solution.**

**Comment by shuvashish76** [comment]
@aloussase libgen is a Shadow library which is clearly Non-Free. Anti-Feature added to F-Droid version.
Would be nice if you could mention the download/upload sources clearly on the description page (fastlane) & Readme.
Currently the sources aren't clear for general users.

**Comment by shuvashish76** [comment]
Thanks for the transparency :)
