### ISSUE TITLE
Implement Libstc as additional source 

### ISSUE THREAD

**Issue by ghost** [aloussase/alexandria-app#7]
There is a possibility of adding Libstc.cc as a source.

It has the biggest quantity of books and scientific papers in the world

The creators are over at Telegram:
https://t.me/nexus_search

**Comment by aloussase** [comment]
Hi, thanks for the suggestions, I will consider it after getting more familiar with Libstc.cc

**Comment by aloussase** [comment]
Hi again, please see #17
